name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    types: ["closed"]
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t ${{ github.repository }} .
      - name: Deploy image
        run: |
          docker stop ${{ github.event.repository.name }} || true
          docker rm ${{ github.event.repository.name }} || true
          docker run ${{ github.event.repository.name }}
          docker run -p 127.0.0.1:2021:2021 -e "DATABASE_URL=${{ secrets.DATABASE_URL }}" --network api --ip 172.0.0.5 -d --name ${{ github.event.repository.name }} ${{ github.repository }}